# Generated by Django 5.2.5 on 2025-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KV',
            fields=[
                ('pk', models.CompositePrimaryKey('queue', 'key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('queue', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.BinaryField()),
            ],
            options={
                'verbose_name': 'KV',
                'verbose_name_plural': 'KVs',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'indexes': [models.Index(fields=['queue', 'timestamp'], name='schedule_queue_ts')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('priority', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'indexes': [models.Index(models.OrderBy(models.F('priority'), descending=True), models.OrderBy(models.F('id')), name='task_priority_id')],
            },
        ),
    ]
